FROM python:3.6-jessie
RUN apt update

WORKDIR /app
ADD requirements.txt /app/requirements.txt

RUN pip install -r /app/requirements.txt

ADD . /app

ENV PORT 8080
CMD ["gunicorn", "app:app", "--config=config.py"]

# Build for GKE & Register in Docker REgistry
# --
# gcloud builds --project elewa-portal-production submit --tag gcr.io/elewa-portal-production/assessment-reader:v1 .

# -- Inside GKE
# kubectl apply -f app.yaml
# kubectl expose deployment elewa-assessment-reader --type=LoadBalancer --port 80 --target-port 8080
# kubectl get services -l name=elewa-assessment-reader