# docker-compose.yml
version: '3'
services:
  flask:
    image: webapp-flask
    tty: true
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - assessments:/app/assessments
  # Frontend Server (Ingress)
  nginx:
    image: webapp-nginx
    tty: true
    build:
      context: ./srv
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:80
    volumes:
      - assessments:/usr/share/nginx/html/assessments
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - flask
  # Certbot config for Secure SSL - HTTP to HTTPS
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  assessments: {}
