#src: https://runnable.com/docker/python/dockerize-your-flask-application

FROM ubuntu:18.04

MAINTAINER Jente Rosseel "jente@elewa.co.ke"

RUN apt-get update -y && \
  apt-get install -y python-pip python-dev

# We copy just the requirements.txt first to leverage Docker cache
COPY ./requirements.txt /app/requirements.txt

RUN export GOOGLE_APPLICATION_CREDENTIALS="./sec/elewa_portal_cloud_storage_access_key.json"

WORKDIR /app

RUN pip install -r requirements.txt

COPY . /app

ENTRYPOINT [ "python" ]

CMD [ "app.py" ]